---
- name: deploy the nginx webserver in managed nodes
  hosts: dev_project
  become: yes
  vars:
    web_package: nginx
    web_svc: nginx
    fw_svc: http
  tasks:
    - name: install nginx package in managed nodes
      ansible.builtin.package:
        name: "{{web_package}}"
        state: present
    - name: start and enable nginx webserver
      ansible.builtin.systemd:
        name: "{{web_svc}}"
        state: started
        enabled: yes
    - name: allow http from firewall
      ansible.posix.firewalld:
        service: "{{fw_svc}}"
        state: enabled
        permanent: yes
        immediate: yes
    - name: deploy the template in managed nodes
      ansible.builtin.template:
        src: template-nginx.yaml
        dest: /usr/share/nginx/html/index.html
